/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.Random;

/**
 *
 * @author chrisrk192
 */
public class DicePanel extends javax.swing.JPanel {

    /**
     * Creates new form DicePanel
     */
    public DicePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dicePane = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        d20Val = new javax.swing.JLabel();
        d16Val = new javax.swing.JLabel();
        d16Button = new javax.swing.JButton();
        d8Val = new javax.swing.JLabel();
        d20Button = new javax.swing.JButton();
        d12Val = new javax.swing.JLabel();
        d12Button = new javax.swing.JButton();
        d8Button = new javax.swing.JButton();
        d10Button = new javax.swing.JButton();
        d10Val = new javax.swing.JLabel();
        d2Val = new javax.swing.JLabel();
        d2Button = new javax.swing.JButton();
        d4Button = new javax.swing.JButton();
        d4Val = new javax.swing.JLabel();
        d6Button = new javax.swing.JButton();
        d6Val = new javax.swing.JLabel();
        d100Button = new javax.swing.JButton();
        d100Val = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        rollHirsory = new javax.swing.JTextArea();

        dicePane.setBackground(new java.awt.Color(204, 204, 204));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        d20Val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d20Val.setText("0");

        d16Val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d16Val.setText("0");

        d16Button.setText("d16");
        d16Button.setMaximumSize(new java.awt.Dimension(57, 23));
        d16Button.setMinimumSize(new java.awt.Dimension(57, 23));
        d16Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d16ButtonActionPerformed(evt);
            }
        });

        d8Val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d8Val.setText("0");

        d20Button.setText("d20");
        d20Button.setMaximumSize(new java.awt.Dimension(57, 23));
        d20Button.setMinimumSize(new java.awt.Dimension(57, 23));
        d20Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d20ButtonActionPerformed(evt);
            }
        });

        d12Val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d12Val.setText("0");

        d12Button.setText("d12");
        d12Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d12ButtonActionPerformed(evt);
            }
        });

        d8Button.setText("d8");
        d8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d8ButtonActionPerformed(evt);
            }
        });

        d10Button.setText("d10");
        d10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d10ButtonActionPerformed(evt);
            }
        });

        d10Val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d10Val.setText("0");

        d2Val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d2Val.setText("0");

        d2Button.setText("d2");
        d2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ButtonActionPerformed(evt);
            }
        });

        d4Button.setText("d4");
        d4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ButtonActionPerformed(evt);
            }
        });

        d4Val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d4Val.setText("0");

        d6Button.setText("d6");
        d6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d6ButtonActionPerformed(evt);
            }
        });

        d6Val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d6Val.setText("0");

        d100Button.setText("d100");
        d100Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d100ButtonActionPerformed(evt);
            }
        });

        d100Val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d100Val.setText("0");

        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("ROLL HISTORY");

        rollHirsory.setEditable(false);
        rollHirsory.setColumns(20);
        rollHirsory.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        rollHirsory.setRows(5);
        jScrollPane1.setViewportView(rollHirsory);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel73, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel24Layout.createSequentialGroup()
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(d6Val, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d4Val, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d2Val, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(d100Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d20Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d16Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(d100Val, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d20Val, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d16Val, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(d12Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(d12Val, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d10Val, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d8Val, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(d6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d100Button)
                    .addComponent(d20Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d16Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d100Val)
                    .addComponent(d20Val)
                    .addComponent(d16Val))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d12Button)
                    .addComponent(d10Button)
                    .addComponent(d8Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d12Val)
                    .addComponent(d10Val)
                    .addComponent(d8Val))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d6Button)
                    .addComponent(d4Button)
                    .addComponent(d2Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d6Val)
                    .addComponent(d4Val)
                    .addComponent(d2Val))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel73)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dicePaneLayout = new javax.swing.GroupLayout(dicePane);
        dicePane.setLayout(dicePaneLayout);
        dicePaneLayout.setHorizontalGroup(
            dicePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dicePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dicePaneLayout.setVerticalGroup(
            dicePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dicePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dicePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dicePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void d16ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d16ButtonActionPerformed
        int val = GenerateRandom(16);
        d16Val.setText(val+"");
        rollHirsory.setText(rollHirsory.getText()+"\nd16  value:   "+val);
    }//GEN-LAST:event_d16ButtonActionPerformed

    private void d20ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d20ButtonActionPerformed
        int val = GenerateRandom(20);
        d20Val.setText(val+"");
        rollHirsory.setText(rollHirsory.getText()+"\nd20  value:   "+val);
    }//GEN-LAST:event_d20ButtonActionPerformed

    private void d12ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d12ButtonActionPerformed
        int val = GenerateRandom(12);
        d12Val.setText(val+"");
        rollHirsory.setText(rollHirsory.getText()+"\nd12  value:   "+val);
    }//GEN-LAST:event_d12ButtonActionPerformed

    private void d8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d8ButtonActionPerformed
        int val = GenerateRandom(8);
        d8Val.setText(val+"");
        rollHirsory.setText(rollHirsory.getText()+"\nd8   value:   "+val);
    }//GEN-LAST:event_d8ButtonActionPerformed

    private void d10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d10ButtonActionPerformed
        int val = GenerateRandom(10);
        d10Val.setText(val+"");
        rollHirsory.setText(rollHirsory.getText()+"\nd10  value:   "+val);
    }//GEN-LAST:event_d10ButtonActionPerformed

    private void d2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ButtonActionPerformed
        int val = GenerateRandom(2);
        d2Val.setText(val+"");
        rollHirsory.setText(rollHirsory.getText()+"\nd2   value:   "+val);
    }//GEN-LAST:event_d2ButtonActionPerformed

    private void d4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ButtonActionPerformed
        int val = GenerateRandom(4);
        d4Val.setText(val+"");
        rollHirsory.setText(rollHirsory.getText()+"\nd4   value:   "+val);
    }//GEN-LAST:event_d4ButtonActionPerformed

    private void d6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d6ButtonActionPerformed
        int val = GenerateRandom(6);
        d6Val.setText(val+"");
        rollHirsory.setText(rollHirsory.getText()+"\nd6   value:   "+val);
    }//GEN-LAST:event_d6ButtonActionPerformed

    private void d100ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d100ButtonActionPerformed
        int val = GenerateRandom(100);
        d100Val.setText(val+"");
        rollHirsory.setText(rollHirsory.getText()+"\nd100 value:   "+val);
    }//GEN-LAST:event_d100ButtonActionPerformed

    private int GenerateRandom(int upperInclusive){
        Random rand =  new Random();
        int randomNum = rand.nextInt((upperInclusive - 1) + 1) + 1;
        return randomNum;
    } 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton d100Button;
    private javax.swing.JLabel d100Val;
    private javax.swing.JButton d10Button;
    private javax.swing.JLabel d10Val;
    private javax.swing.JButton d12Button;
    private javax.swing.JLabel d12Val;
    private javax.swing.JButton d16Button;
    private javax.swing.JLabel d16Val;
    private javax.swing.JButton d20Button;
    private javax.swing.JLabel d20Val;
    private javax.swing.JButton d2Button;
    private javax.swing.JLabel d2Val;
    private javax.swing.JButton d4Button;
    private javax.swing.JLabel d4Val;
    private javax.swing.JButton d6Button;
    private javax.swing.JLabel d6Val;
    private javax.swing.JButton d8Button;
    private javax.swing.JLabel d8Val;
    private javax.swing.JPanel dicePane;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea rollHirsory;
    // End of variables declaration//GEN-END:variables
}
