/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.CharacterSheet;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author chrisrk192
 */
public class NewCharacter extends javax.swing.JFrame {

    private static Data.CharacterSheet cs;
    public static PlayerSheet returnTo;
    /**
     * Creates new form NewCharacter
     */
    public NewCharacter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel90 = new javax.swing.JPanel();
        jPanel135 = new javax.swing.JPanel();
        jLabel184 = new javax.swing.JLabel();
        raceComboBox = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        raceDescriptionArea = new javax.swing.JTextArea();
        jPanel91 = new javax.swing.JPanel();
        jPanel136 = new javax.swing.JPanel();
        jLabel185 = new javax.swing.JLabel();
        classComboBox = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        classDescriptionArea = new javax.swing.JTextArea();
        jLabel183 = new javax.swing.JLabel();
        newCharNameField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        finalizeCharacterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Character");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel90.setBackground(new java.awt.Color(204, 204, 204));

        jPanel135.setBackground(new java.awt.Color(255, 255, 255));

        jLabel184.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel184.setText("RACE");

        raceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        raceComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                raceComboBoxPropertyChange(evt);
            }
        });

        raceDescriptionArea.setEditable(false);
        raceDescriptionArea.setColumns(20);
        raceDescriptionArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        raceDescriptionArea.setLineWrap(true);
        raceDescriptionArea.setRows(5);
        raceDescriptionArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(raceDescriptionArea);

        javax.swing.GroupLayout jPanel135Layout = new javax.swing.GroupLayout(jPanel135);
        jPanel135.setLayout(jPanel135Layout);
        jPanel135Layout.setHorizontalGroup(
            jPanel135Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel135Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel135Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(jLabel184, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(raceComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel135Layout.setVerticalGroup(
            jPanel135Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel135Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(raceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel184))
        );

        javax.swing.GroupLayout jPanel90Layout = new javax.swing.GroupLayout(jPanel90);
        jPanel90.setLayout(jPanel90Layout);
        jPanel90Layout.setHorizontalGroup(
            jPanel90Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel90Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel135, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel90Layout.setVerticalGroup(
            jPanel90Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel90Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel135, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel91.setBackground(new java.awt.Color(204, 204, 204));
        jPanel91.setPreferredSize(new java.awt.Dimension(400, 175));

        jPanel136.setBackground(new java.awt.Color(255, 255, 255));

        jLabel185.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel185.setText("CLASS");

        classComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        classComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                classComboBoxPropertyChange(evt);
            }
        });

        classDescriptionArea.setEditable(false);
        classDescriptionArea.setColumns(20);
        classDescriptionArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        classDescriptionArea.setLineWrap(true);
        classDescriptionArea.setRows(5);
        classDescriptionArea.setWrapStyleWord(true);
        jScrollPane5.setViewportView(classDescriptionArea);

        javax.swing.GroupLayout jPanel136Layout = new javax.swing.GroupLayout(jPanel136);
        jPanel136.setLayout(jPanel136Layout);
        jPanel136Layout.setHorizontalGroup(
            jPanel136Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel136Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel136Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(jLabel185, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel136Layout.setVerticalGroup(
            jPanel136Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel136Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel185))
        );

        javax.swing.GroupLayout jPanel91Layout = new javax.swing.GroupLayout(jPanel91);
        jPanel91.setLayout(jPanel91Layout);
        jPanel91Layout.setHorizontalGroup(
            jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel91Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel136, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel91Layout.setVerticalGroup(
            jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel91Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel136, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel183.setText("Name");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        finalizeCharacterButton.setText("Accept");
        finalizeCharacterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeCharacterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finalizeCharacterButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel91, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel183, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCharNameField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel183)
                    .addComponent(newCharNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel91, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(finalizeCharacterButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finalizeCharacterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizeCharacterButtonActionPerformed
        // TODO add your handling code here:
        cs = new CharacterSheet();
        String name = newCharNameField.getText();
        String classs = classComboBox.getItemAt(classComboBox.getSelectedIndex());
        String race = raceComboBox.getItemAt(raceComboBox.getSelectedIndex());
        if(name.compareTo("") == 0)
            return;      
        if(classs.compareTo("") == 0)
            return;
        if(race.compareTo("") == 0)
            return;
        cs.name = name;
        cs.race = race;
        cs.classs = classs;
        //Main.playerActiveChar = cs;
        returnTo.AddPlayerCharacter(cs);
        this.dispose();
                
    }//GEN-LAST:event_finalizeCharacterButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        raceComboBox.setModel(PopulateRaces());
        classComboBox.setModel(PopulateClasses());
    }//GEN-LAST:event_formWindowActivated

    private void classComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_classComboBoxPropertyChange
        // TODO add your handling code here:
        //class selected, load the json file, populate text area
        classDescriptionArea.setText("");
        //classComboBox.item
        String selected = (String)classComboBox.getSelectedItem();
        System.out.println(selected);
        String theJSON;
        if(selected.compareTo("Item 1") != 0){
            theJSON = Data.IO.LoadJSONFile(Data.IO.classDir+"/"+selected+".ser");
            Data.ClassArchtype classs = Data.DataCollection.FilterClassArchTypeJSON(theJSON);
            String choices = "";
            String profis = "";
            String saving = "";
             for(int i = 0; i < classs.savingThrows.size(); i++){
                saving+="   "+classs.savingThrows.get(i).name+"\n";
            }
            for(int i = 0; i < classs.proficiencies.size(); i++){
                profis+="   "+classs.proficiencies.get(i).name+"\n";
            }
            for(int i = 0; i < classs.profcncyChoices.size(); i++){
                choices+="   "+classs.profcncyChoices.get(i).name+"\n";
            }
            classDescriptionArea.setText(
                    "Hit Die: "+classs.hitDie+"\n\n"+
                    "Choices: Choose "+classs.numProfcncyToChoose+"\n"+choices+'\n'+
                    "Proficiencies:\n"+profis+"\n"+
                    "Saving Throws:\n"+saving+"\n"
            );
            
                    
        }
        
        //Data.IO.LoadJSONFile(Data.IO.classDir+"/"+selected+".ser");
    }//GEN-LAST:event_classComboBoxPropertyChange

    private void raceComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_raceComboBoxPropertyChange
        // TODO add your handling code here:
        raceDescriptionArea.setText("");
        //classComboBox.item
        String selected = (String)raceComboBox.getSelectedItem();
        System.out.println(selected);
        String theJSON;
        if(selected.compareTo("Item 1") != 0){
            theJSON = Data.IO.LoadJSONFile(Data.IO.raceDir+"/"+selected+".ser");
            Data.Race race = Data.DataCollection.FilterRaceJSON(theJSON);
           
            raceDescriptionArea.setText(
                    "Alignment: \n   "+race.alignment+"\n"+
                    "Size: \n   "+race.size+"\n"+
                    "Speed: \n   "+race.speed+"\n"+
                    "Age: \n   "+race.alignment+"\n");
            
            raceDescriptionArea.setText(raceDescriptionArea.getText()+
                    "Traits: \n");
            for(int i = 0; i < race.traits.size(); i++)        
                raceDescriptionArea.setText(raceDescriptionArea.getText()+
                        "   "+race.traits.get(i).name+"\n");
            
            raceDescriptionArea.setText(raceDescriptionArea.getText()+
                    "Proficiencies: \n");
            for(int i = 0; i < race.starting_proficiencies.size(); i++)        
                raceDescriptionArea.setText(raceDescriptionArea.getText()+
                        "   "+race.starting_proficiencies.get(i).name+"\n");
            
            raceDescriptionArea.setText(raceDescriptionArea.getText()+
                    "Proficiency Choices: "+"Choose "+race.choose);
            for(int i = 0; i < race.from.size(); i++)        
                raceDescriptionArea.setText(raceDescriptionArea.getText()+
                        "   "+race.from.get(i).name+"\n");
            
            raceDescriptionArea.setText(raceDescriptionArea.getText()+
                            "Languages:\n"+race.language_desc+"\n"); 
            for(int i = 0; i < race.languages.size(); i++)        
                raceDescriptionArea.setText(raceDescriptionArea.getText()+
                        "   "+race.languages.get(i).name+"\n");       
        }
    }//GEN-LAST:event_raceComboBoxPropertyChange

    
    private ComboBoxModel<String> PopulateClasses(){
        DefaultComboBoxModel<String> listModel = new DefaultComboBoxModel<>();
        ArrayList<String> fn = Data.IO.GetFileNames(Data.IO.classDir);
        for (int i = 0; i < fn.size(); i++) {
            if(fn.get(i).contains(".ser"))
                listModel.addElement(fn.get(i).replace(".ser", ""));    
        }        
        return listModel;
    }
    private ComboBoxModel<String> PopulateRaces(){
        DefaultComboBoxModel<String> listModel = new DefaultComboBoxModel<>();
        ArrayList<String> fn = Data.IO.GetFileNames(Data.IO.raceDir);
        for (int i = 0; i < fn.size(); i++) {
            listModel.addElement(fn.get(i).replace(".ser", ""));    
        }        
        return listModel;
    }
    /**
     * @param args the command line arguments
     */
    public static void ShowDialog(String args[]) {
        
        cs = new Data.CharacterSheet();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCharacter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> classComboBox;
    private javax.swing.JTextArea classDescriptionArea;
    private javax.swing.JButton finalizeCharacterButton;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JPanel jPanel135;
    private javax.swing.JPanel jPanel136;
    private javax.swing.JPanel jPanel90;
    private javax.swing.JPanel jPanel91;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField newCharNameField;
    private javax.swing.JComboBox<String> raceComboBox;
    private javax.swing.JTextArea raceDescriptionArea;
    // End of variables declaration//GEN-END:variables
}
