/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.DataUrl;
import Data.Spell;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author chrisrk192
 */
public class NewSpell extends javax.swing.JFrame {
    public Data.Spell currentSpell;
    /**
     * Creates new form NewSpell
     */
    public NewSpell() {
        currentSpell = new Spell();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel156 = new javax.swing.JPanel();
        jPanel157 = new javax.swing.JPanel();
        jLabel345 = new javax.swing.JLabel();
        jLabel346 = new javax.swing.JLabel();
        jLabel347 = new javax.swing.JLabel();
        jLabel348 = new javax.swing.JLabel();
        jLabel349 = new javax.swing.JLabel();
        jLabel351 = new javax.swing.JLabel();
        jLabel352 = new javax.swing.JLabel();
        jLabel354 = new javax.swing.JLabel();
        jScrollPane52 = new javax.swing.JScrollPane();
        refSpellDicr1 = new javax.swing.JTextArea();
        jScrollPane50 = new javax.swing.JScrollPane();
        materials = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        school = new javax.swing.JTextField();
        castingTime = new javax.swing.JTextField();
        range = new javax.swing.JTextField();
        duration = new javax.swing.JTextField();
        ritual = new javax.swing.JTextField();
        level = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jLabel353 = new javax.swing.JLabel();
        higher = new javax.swing.JTextField();
        concen = new javax.swing.JTextField();
        jLabel355 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel156.setBackground(new java.awt.Color(204, 204, 204));

        jPanel157.setBackground(new java.awt.Color(255, 255, 255));

        jLabel345.setText("SPELL DISCRIPTION");

        jLabel346.setText("NAME:");

        jLabel347.setText("SCHOOL:");

        jLabel348.setText("CASTING TIME:");

        jLabel349.setText("RANGE:");

        jLabel351.setText("DURATION:");

        jLabel352.setText("RITUAL:");

        jLabel354.setText("LEVEL:");

        refSpellDicr1.setColumns(20);
        refSpellDicr1.setLineWrap(true);
        refSpellDicr1.setRows(5);
        refSpellDicr1.setWrapStyleWord(true);
        jScrollPane52.setViewportView(refSpellDicr1);

        materials.setColumns(20);
        materials.setLineWrap(true);
        materials.setRows(5);
        materials.setWrapStyleWord(true);
        jScrollPane50.setViewportView(materials);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MATERIALS");

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3", "Level 4", "Level 5", "Level 6", "Level 7", "Level 8", "Level 9" }));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Components");

        jTextField1.setText("V,S,M");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Classes");

        jCheckBox1.setText("Barbarian");

        jCheckBox2.setText("Bard");

        jCheckBox3.setText("Cleric");

        jCheckBox4.setText("Druid");

        jCheckBox5.setText("Fighter");

        jCheckBox6.setText("Monk");

        jCheckBox7.setText("Paladin");

        jCheckBox8.setText("Ranger");

        jCheckBox9.setText("Rogue");

        jCheckBox10.setText("Sorcerer");

        jCheckBox11.setText("Warlock");

        jCheckBox12.setText("Wizard");

        jLabel353.setText("Higher Level:");

        jLabel355.setText("Concentration:");

        javax.swing.GroupLayout jPanel157Layout = new javax.swing.GroupLayout(jPanel157);
        jPanel157.setLayout(jPanel157Layout);
        jPanel157Layout.setHorizontalGroup(
            jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel157Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane52)
                    .addGroup(jPanel157Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel157Layout.createSequentialGroup()
                        .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel157Layout.createSequentialGroup()
                                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCheckBox9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCheckBox11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane50, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel345, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel157Layout.createSequentialGroup()
                        .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel355, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel353, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel346, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel347, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel352, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel348, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel349, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel351, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel354, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(castingTime)
                            .addComponent(range)
                            .addComponent(duration)
                            .addComponent(ritual)
                            .addComponent(school)
                            .addComponent(level, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name)
                            .addComponent(higher)
                            .addComponent(concen))))
                .addContainerGap())
        );
        jPanel157Layout.setVerticalGroup(
            jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel157Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel346)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel347)
                    .addComponent(school, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel354)
                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel348)
                    .addComponent(castingTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel349)
                    .addComponent(range, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel351)
                    .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel352)
                    .addComponent(ritual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel353)
                    .addComponent(higher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel355)
                    .addComponent(concen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel345)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane52, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel157Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel157Layout.createSequentialGroup()
                        .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel157Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane50)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel157Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel156Layout = new javax.swing.GroupLayout(jPanel156);
        jPanel156.setLayout(jPanel156Layout);
        jPanel156Layout.setHorizontalGroup(
            jPanel156Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel156Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel157, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel156Layout.setVerticalGroup(
            jPanel156Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel156Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel157, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel156, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel156, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(name.getText().compareTo("")==0){
             JOptionPane.showMessageDialog(null, "Name can not be empty", "Warning", JOptionPane.ERROR_MESSAGE);
             return;
         }
         currentSpell.name = name.getText();
         currentSpell.level = level.getSelectedIndex()+1;
         currentSpell.school = new DataUrl(school.getText(), "", 0);
         currentSpell.casting_time = castingTime.getText();
         currentSpell.range = range.getText();
         currentSpell.duration = duration.getText();
         currentSpell.ritual = ritual.getText();
         currentSpell.higher_level = new ArrayList<>();
         currentSpell.higher_level.add(higher.getText());
         currentSpell.concentration = concen.getText();
         ArrayList<String> d = new ArrayList<>();
         
         d.add(refSpellDicr1.getText());
         currentSpell.desc = d;
         currentSpell.material = materials.getText();
         
         Data.IO.SaveJSONFile(SpellToJSON(currentSpell), Data.IO.spellDir+"/"+currentSpell.name+".ser");
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public String SpellToJSON(Data.Spell s){
        String classArray = "";//"{\"name\":\"Cleric\",\"url\":\"http://www.dnd5eapi.co/api/classes/3\"},{\"name\":\"Paladin\",\"url\":\"http://www.dnd5eapi.co/api/classes/7\"}";
        String componentArray = "";//"{\"V\",\"S\",\"M\"}";
        
        String theJSON = "{\"_id\":\"\",\"index\":\"\",\"name\":\"__NAME__\","
                + "\"desc\":[\"__DESC__\"],\"higher_level\":[\"__HIGHER__\"],"
                + "\"page\":\"__PAGE__\",\"range\":\"__RANGE__\","
                + "\"components\":[__COMPONENT_ARRAY__],"
                + "\"material\":\"__MATERIAL__\",\"ritual\":\"__RITUAL__\","
                + "\"duration\":\"__DURATION__\",\"concentration\":\"__CONCENTRATION__\","
                + "\"casting_time\":\"__CASTINGTIME__\",\"level\":__LEVEL__,"
                + "\"school\":{\"url\":\"__SCHOOLURL__\",\"name\":\"__SCHOOL__\"},"
                + "\"classes\":[__CLASSES_ARRAY__],\"subclasses\":[{\"url\":\"__SUBCLASSURL__\",\"name\":\"__SUBCLASS__\"}],"
                + "\"url\":\"__URL__\"}";        
        
              
        
        theJSON = theJSON.replace("__NAME__", s.name);
        theJSON = theJSON.replace("__DESC__", s.desc.get(0));
        theJSON = theJSON.replace("__HIGHER__", s.higher_level.get(0));
        theJSON = theJSON.replace("__RANGE__", s.range);
        theJSON = theJSON.replace("__MATERIAL__", s.material);
        theJSON = theJSON.replace("__RITUAL__", s.ritual);
        theJSON = theJSON.replace("__DURATION__", s.duration);
        theJSON = theJSON.replace("__CONCENTRATION__", s.concentration);
        theJSON = theJSON.replace("__CASTINGTIME__", s.casting_time);
        theJSON = theJSON.replace("__LEVEL__", s.duration);
        theJSON = theJSON.replace("__SCHOOL__", s.school.name);
        theJSON = theJSON.replace("__SCHOOLURL__", s.school.url);
        theJSON = theJSON.replace("__SUBCLASS__", s.school.name);
        theJSON = theJSON.replace("__URL__", s.school.url);
        
        
        
        
        
        String[] comps = jTextField1.getText().split(",");
        
        if(comps.length > 1){
            componentArray = "\""+comps[0]+"\",";

            for(int i = 1; i < comps.length-1; i++){
                componentArray = componentArray + "\"" +comps[i] + "\",";
            }
            componentArray = componentArray + "\"" +comps[comps.length-1] + "\"";
        } else{
            componentArray = "{\""+comps[0]+"\"";
        }
        theJSON = theJSON.replace("__COMPONENT_ARRAY__", componentArray);
        
        //     "{\"name\":\"Cleric\",\"url\":\"http://www.dnd5eapi.co/api/classes/3\"},{\"name\":\"Paladin\",\"url\":\"http://www.dnd5eapi.co/api/classes/7\"}";
        classArray = "";
        int numClasses = 0;
        
        if(jCheckBox1.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Barbarian\",\"url\":\"http://www.dnd5eapi.co/api/classes/1\"},";
        }
        if(jCheckBox2.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Bard\",\"url\":\"http://www.dnd5eapi.co/api/classes/2\"},";
        }
        if(jCheckBox3.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Cleric\",\"url\":\"http://www.dnd5eapi.co/api/classes/3\"},";
        }
        if(jCheckBox4.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Druid\",\"url\":\"http://www.dnd5eapi.co/api/classes/4\"},";
        }
        if(jCheckBox5.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Fighter\",\"url\":\"http://www.dnd5eapi.co/api/classes/5\"},";
        }
        if(jCheckBox6.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Monk\",\"url\":\"http://www.dnd5eapi.co/api/classes/6\"},";
        }
        if(jCheckBox7.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Paladin\",\"url\":\"http://www.dnd5eapi.co/api/classes/7\"},";
        }
        if(jCheckBox8.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Ranger\",\"url\":\"http://www.dnd5eapi.co/api/classes/8\"},";
        }
        if(jCheckBox9.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Rogue\",\"url\":\"http://www.dnd5eapi.co/api/classes/9\"},";
        }
        if(jCheckBox10.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Sorcerer\",\"url\":\"http://www.dnd5eapi.co/api/classes/10\"},";
        }
        if(jCheckBox11.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Warlock\",\"url\":\"http://www.dnd5eapi.co/api/classes/11\"},";
        }
        if(jCheckBox12.isSelected()){
            numClasses++;
            classArray = classArray + "{\"name\":\"Wizard\",\"url\":\"http://www.dnd5eapi.co/api/classes/12\"},";
        }
        
        classArray = classArray.substring(0, classArray.length()-1);
        
        
        theJSON = theJSON.replace("__CLASSES_ARRAY__", classArray);
        System.out.println(theJSON);
        return theJSON;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSpell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSpell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSpell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSpell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewSpell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField castingTime;
    private javax.swing.JTextField concen;
    private javax.swing.JTextField duration;
    private javax.swing.JTextField higher;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel345;
    private javax.swing.JLabel jLabel346;
    private javax.swing.JLabel jLabel347;
    private javax.swing.JLabel jLabel348;
    private javax.swing.JLabel jLabel349;
    private javax.swing.JLabel jLabel351;
    private javax.swing.JLabel jLabel352;
    private javax.swing.JLabel jLabel353;
    private javax.swing.JLabel jLabel354;
    private javax.swing.JLabel jLabel355;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel156;
    private javax.swing.JPanel jPanel157;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JScrollPane jScrollPane52;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JTextArea materials;
    private javax.swing.JTextField name;
    private javax.swing.JTextField range;
    private javax.swing.JTextArea refSpellDicr1;
    private javax.swing.JTextField ritual;
    private javax.swing.JTextField school;
    // End of variables declaration//GEN-END:variables
}
